### ISSUE TITLE
unicode latin-1 encoding

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-agrovoc-importer#2]
When importing GEMET or AGROVOC thesauries the encoding is broken. Geonode exception, when trying to set one tkeyword via geonode api:
```
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 4821: Body ('’') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.
```

**Comment by mwallschlaeger** [comment]
its fixed with latest changes to this repository. Or in other words, after using the latest update I cannot reproduce the error

**Comment by specka** [comment]
Will be testet, if the mother issue (small epic: https://github.com/zalf-rdm/OpenResearchData_Migration/issues/15) will be fixed.
