### ISSUE TITLE
Feature: impl. switch to force lower case writing of all keywords

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNodeUserGroup-DE/geonode-agrovoc-importer#3]
When loading keywords into geonode it's hard to find them after words, as the geonode v2/api `filter` method is case sensitive. Therefore finding back keywords this way is very hard. Therefore, a force lower-case parameter would be appreciated.

**Comment by specka** [comment]
Will be testet, if the mother issue (small epic: https://github.com/zalf-rdm/OpenResearchData_Migration/issues/15) will be fixed.
